import { useAuth } from '@/hooks/useAuth'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import axios from '@/lib/axios'

export default function Home() {
  const {user,  login } = useAuth({
      middleware: 'guest',
  })

  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head> 
      <>
        <p>Home</p>
        <button onClick={registerUser}>Login</button>
      </>
    </>
  )
}
